# -*- coding: utf-8 -*-
"""Question3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YVOCL9C76vt4R-s8qQEwEghsXb9tetfO
"""

from google.colab import drive
drive.mount('/content/drive/')

import os
import tables

header_1 = "/content/drive/My Drive/MCA - Assignment 1/"
header_2 = "/content/drive/My Drive/IIITD Stuff/MCA - Assignment 1/"

img_path = os.path.join(header_2, "images")
query_path = os.path.join(header_2, "train/query")
ground_truth_path = os.path.join(header_2, "train/ground_truth")
data_path = os.path.join(header_2, "Shwetank's Code/models/log_2")
query_output_path = os.path.join(header_2, "Shwetank's Code/queries/log_2")

import cv2
import numpy as np
from skimage.feature import hessian_matrix_det
import pickle
import matplotlib.pyplot as plt
import math

imgs  = os.listdir(img_path)
imgs_base = [x.split('.')[0] for x in imgs]
print(str(len(imgs_base)) + " images received.")

count = 1
for node_name in imgs_base:
    print('processing file:' + str(count))
    count+=1
    img_file = node_name + ".jpg"
    im = cv2.imread(os.path.join(img_path, img_file), 0)
    h, w = im.shape
    ratio = min(100 / h, 100 / w)
    h = int(h * ratio)
    w = int(w * ratio)
    im = cv2.resize(im, (w, h))
    im = np.array(im)
    im = im / 255.0

    im_hess = hessian_matrix_det(im, 2, True)
    
    fig, ax = plt.subplots(2)
    ax[0].imshow(im, interpolation='nearest',cmap="gray")
    ax[1].imshow(im_hess, interpolation='nearest',cmap="gray")
    plt.show()
    break

